version: "3"
services:
  test-local:
    image: lambda-go-autentication:latest
    build:
      context: ../
      dockerfile: ./Dockerfile
    ports:
      - "9000:8080"
    volumes:
      - ../.aws-lambda-rie:/aws-lambda
    command: "/app/main" # Using "/app/main" as the command to execute the lambda test locally.
    entrypoint: /aws-lambda/aws-lambda-rie # Utilizing the RIE as the entrypoint for local lambda testing.
    environment:
      - APP_NAME=lambda-go-autentication
      - REGION=us-east-2
      - VERSION=1.0
      - JWT_KEY=my_secret_key
      - SSM_JWT_KEY=key-secret
      - TABLE_NAME=user_login_2
      - OTEL_EXPORTER_OTLP_ENDPOINT=localhost:4317
      - AWS_REGION=us-east-2
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_SESSION_TOKEN=
